---
output: 
  md_document:
    variant: markdown_github
---

## Transparencias del trabajo en equipo de la asignatura "Big Data"

Repo utilizado para elaborar las transparencias del trabajo en equipo para la asignatura "Programación y manejo de datos en la era del Big Data" de la Universitat de València durante el curso 2021-2022. La página web de la asignatura puede verse aquí: <https://perezp44.github.io/intro-ds-20-21-web/>.

La versión final de estas transparencias puede visualizarse en: <https://AlicjaMl.github.io/_trabajo_BigData_slides/>.

La versión final del trabajo puede visualizarse en: <https://AlicjaMl.github.io/_trabajo_BigData_equipo/>.

El título del trabajo es: Análisis de las mejores 100 universidades del mundo.  Nuestro objetivo es hacer un estudio de la evolución respecto a diferentes variables de tres dataset que contienen diferentes rankings de las mejores 100 universidades del mundo desde el año 2012 hasta 2015.
Planteamos preguntas como qué país tiene más universidades en el ranking, cuál es el número de estudiantes en las mejores universidades, o la relación entre la posición de una universidad en el ránking con su posición respecto al nivel de educación o el número de publicaciones. 

Además, queremos mostrar la información de manera más visual mediante gráficos dinámicos comparando la evolución de las universidades en el top 10 durante los años, la posición de los diferentes países en el ránking, así como su evolución a lo largo del tiempo. 
